# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - repertoire

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_36F5FB0DE7C94E9DB5C95614C0750610 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF790FA20AA944678B96914C3414DC0D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0CB853568A504091BCFD46DFF970D2E6 }}

      - name: Set Azure App Settings (MySQL)
        run: |
          az webapp config appsettings set --name repertoire \
            --resource-group YOUR_RESOURCE_GROUP_NAME \
            --settings SPRING_DATASOURCE_URL="jdbc:mysql://repertoire-webservice-mysql-server-az-students.mysql.database.azure.com:3306/catalogue_api?useSSL=true&serverTimezone=UTC" \
                     SPRING_DATASOURCE_USERNAME="admin_user@repertoire-webservice-mysql-server-az-students" \
                     SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}"
        shell: bash

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'repertoire'
          slot-name: 'Production'
          package: '*.war'

          
